name: Create docker image
on:
  push:
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
   
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1      
    -
      id: modify
      name: Modify scripts and get version
      run: |
        output=$(date -u '+%Y%m%d%H%M%S')
        echo ::set-output name=date_version::$output
    -
      name: version
      run: echo "Version ${{steps.modify.outputs.date_version}}"
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:        
        context: .devcontainer
        push: true
        tags: |
          ghcr.io/${{github.repository}}:latest
          ghcr.io/${{github.repository}}:${{steps.modify.outputs.date_version}}
